server:
  port: 8084
  
spring:
  application:
    name: service-cloud-eureka-ribbon
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true