server:
  port: 8083
  
spring:
  application:
    name: service-cloud-eureka-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true